package com.iridium.iridiumskyblock.configs;

import com.iridium.iridiumskyblock.commands.*;

public class Commands {
    public CreateCommand createCommand = new CreateCommand();
    public HomeCommand homeCommand = new HomeCommand();
    public DeleteCommand deleteCommand = new DeleteCommand();
    public ReloadCommand reloadCommand = new ReloadCommand();
    public RegenCommand regenCommand = new RegenCommand();
    public InviteCommand inviteCommand = new InviteCommand();
    public JoinCommand joinCommand = new JoinCommand();
    public MissionsCommand missionsCommand = new MissionsCommand();
    public UpgradeCommand upgradeCommand = new UpgradeCommand();
    public BoosterCommand boosterCommand = new BoosterCommand();
    public CrystalsCommand crystalsCommand = new CrystalsCommand();
    public GiveCrystalsCommand giveCrystalsCommand = new GiveCrystalsCommand();
    public RemoveCrystalsCommand removeCrystalsCommand = new RemoveCrystalsCommand();
    public MembersCommand membersCommand = new MembersCommand();
    public FlyCommand flyCommand = new FlyCommand();
    public AboutCommand aboutCommand = new AboutCommand();
    public WarpsCommand warpsCommand = new WarpsCommand();
    public SetWarpCommand warpCommand = new SetWarpCommand();
    public ValueCommand valueCommand = new ValueCommand();
    public TopCommand topCommand = new TopCommand();
    public LeaveCommand leaveCommand = new LeaveCommand();
    public WorldBorderCommand worldBorderCommand = new WorldBorderCommand();
    public KickCommand kickCommand = new KickCommand();
    public VisitCommand visitCommand = new VisitCommand();
    public PublicCommand publicCommand = new PublicCommand();
    public PrivateCommand privateCommand = new PrivateCommand();
    public BypassCommand bypassCommand = new BypassCommand();
    public SetHomeCommand setHomeCommand = new SetHomeCommand();
    public PermissionsCommand permissionsCommand = new PermissionsCommand();
    public TransferCommand transferCommand = new TransferCommand();
    public AdminCommand adminCommand = new AdminCommand();
    public GiveBoosterCommand giveBoosterCommand = new GiveBoosterCommand();
    public GiveUpgradeCommand giveUpgradeCommand = new GiveUpgradeCommand();
    public BanCommand banCommand = new BanCommand();
    public UnBanCommand unBanCommand = new UnBanCommand();
    public CoopCommand coopCommand = new CoopCommand();
    public UnCoopCommand unCoopCommand = new UnCoopCommand();
    public SetNameCommand setNameCommand = new SetNameCommand();
    public BankCommand bankCommand = new BankCommand();
    public ChatCommand chatCommand = new ChatCommand();
    public ShopCommand shopCommand = new ShopCommand();
    public BiomeCommand biomeCommand = new BiomeCommand();
    public HelpCommand helpCommand = new HelpCommand();
    public LanguagesCommand languagesCommand = new LanguagesCommand();
    public RecalculateCommand recalculateCommand = new RecalculateCommand();
    public AddValueCommand addValueCommand = new AddValueCommand();
    public RemoveValueCommand removeValueCommand = new RemoveValueCommand();
    public ExpelCommand expelCommand = new ExpelCommand();
}
